[build]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/tarot"
  to = "/.netlify/functions/index"
  status = 200

[[redirects]]
  from = "/tarot3"
  to = "/.netlify/functions/index"
  status = 200

[[redirects]]
  from = "/tarotlove"
  to = "/.netlify/functions/index"
  status = 200

[[redirects]]
  from = "/tarotcareer"
  to = "/.netlify/functions/index"
  status = 200

[[redirects]]
  from = "/cunghoangdao"
  to = "/.netlify/functions/index"
  status = 200

[[redirects]]
  from = "/duyen"
  to = "/.netlify/functions/index"
  status = 200

[[redirects]]
  from = "/home"
  to = "/.netlify/functions/index"
  status = 200

[functions]
  node_bundler = "esbuild"
