[build]
  functions = "netlify/functions"
  publish = "public"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/"
  to = "/.netlify/functions/index"
  status = 200

[[redirects]]
  from = "/home"
  to = "/.netlify/functions/index"
  status = 200

[[redirects]]
  from = "/cunghoangdao"
  to = "/.netlify/functions/index"
  status = 200

[[redirects]]
  from = "/duyen"
  to = "/.netlify/functions/index"
  status = 200

[[redirects]]
  from = "/tarot"
  to = "/.netlify/functions/index"
  status = 200
